// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CurrencyExchangeValue.proto

package currencyExchangeValue;

public final class CurrencyExchangeValueOuterClass {
  private CurrencyExchangeValueOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code currencyExchangeValue.Currency}
   */
  public enum Currency
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>PLN = 0;</code>
     */
    PLN(0),
    /**
     * <code>USD = 1;</code>
     */
    USD(1),
    /**
     * <code>EUR = 2;</code>
     */
    EUR(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>PLN = 0;</code>
     */
    public static final int PLN_VALUE = 0;
    /**
     * <code>USD = 1;</code>
     */
    public static final int USD_VALUE = 1;
    /**
     * <code>EUR = 2;</code>
     */
    public static final int EUR_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Currency valueOf(int value) {
      return forNumber(value);
    }

    public static Currency forNumber(int value) {
      switch (value) {
        case 0: return PLN;
        case 1: return USD;
        case 2: return EUR;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Currency>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Currency> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Currency>() {
            public Currency findValueByNumber(int number) {
              return Currency.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return currencyExchangeValue.CurrencyExchangeValueOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Currency[] VALUES = values();

    public static Currency valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Currency(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:currencyExchangeValue.Currency)
  }

  public interface ApplicationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:currencyExchangeValue.Application)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string address = 1;</code>
     */
    java.lang.String getAddress();
    /**
     * <code>string address = 1;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes();

    /**
     * <code>int32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    java.util.List<currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency> getCurrencyList();
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    int getCurrencyCount();
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency getCurrency(int index);
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    java.util.List<java.lang.Integer>
    getCurrencyValueList();
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    int getCurrencyValue(int index);
  }
  /**
   * Protobuf type {@code currencyExchangeValue.Application}
   */
  public  static final class Application extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:currencyExchangeValue.Application)
      ApplicationOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Application.newBuilder() to construct.
    private Application(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Application() {
      address_ = "";
      currency_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Application(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              address_ = s;
              break;
            }
            case 16: {

              port_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                currency_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000004;
              }
              currency_.add(rawValue);
              break;
            }
            case 26: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                if (!((mutable_bitField0_ & 0x00000004) != 0)) {
                  currency_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000004;
                }
                currency_.add(rawValue);
              }
              input.popLimit(oldLimit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) != 0)) {
          currency_ = java.util.Collections.unmodifiableList(currency_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Application_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Application_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              currencyExchangeValue.CurrencyExchangeValueOuterClass.Application.class, currencyExchangeValue.CurrencyExchangeValueOuterClass.Application.Builder.class);
    }

    private int bitField0_;
    public static final int ADDRESS_FIELD_NUMBER = 1;
    private volatile java.lang.Object address_;
    /**
     * <code>string address = 1;</code>
     */
    public java.lang.String getAddress() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        address_ = s;
        return s;
      }
    }
    /**
     * <code>string address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes() {
      java.lang.Object ref = address_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        address_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>int32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int CURRENCY_FIELD_NUMBER = 3;
    private java.util.List<java.lang.Integer> currency_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency> currency_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency>() {
              public currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency result = currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency.valueOf(from);
                return result == null ? currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    public java.util.List<currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency> getCurrencyList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency>(currency_, currency_converter_);
    }
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    public int getCurrencyCount() {
      return currency_.size();
    }
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    public currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency getCurrency(int index) {
      return currency_converter_.convert(currency_.get(index));
    }
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    public java.util.List<java.lang.Integer>
    getCurrencyValueList() {
      return currency_;
    }
    /**
     * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
     */
    public int getCurrencyValue(int index) {
      return currency_.get(index);
    }
    private int currencyMemoizedSerializedSize;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getAddressBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, address_);
      }
      if (port_ != 0) {
        output.writeInt32(2, port_);
      }
      if (getCurrencyList().size() > 0) {
        output.writeUInt32NoTag(26);
        output.writeUInt32NoTag(currencyMemoizedSerializedSize);
      }
      for (int i = 0; i < currency_.size(); i++) {
        output.writeEnumNoTag(currency_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAddressBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, address_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, port_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < currency_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(currency_.get(i));
        }
        size += dataSize;
        if (!getCurrencyList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }currencyMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof currencyExchangeValue.CurrencyExchangeValueOuterClass.Application)) {
        return super.equals(obj);
      }
      currencyExchangeValue.CurrencyExchangeValueOuterClass.Application other = (currencyExchangeValue.CurrencyExchangeValueOuterClass.Application) obj;

      if (!getAddress()
          .equals(other.getAddress())) return false;
      if (getPort()
          != other.getPort()) return false;
      if (!currency_.equals(other.currency_)) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
      hash = (53 * hash) + getAddress().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      if (getCurrencyCount() > 0) {
        hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
        hash = (53 * hash) + currency_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(currencyExchangeValue.CurrencyExchangeValueOuterClass.Application prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code currencyExchangeValue.Application}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:currencyExchangeValue.Application)
        currencyExchangeValue.CurrencyExchangeValueOuterClass.ApplicationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Application_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Application_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                currencyExchangeValue.CurrencyExchangeValueOuterClass.Application.class, currencyExchangeValue.CurrencyExchangeValueOuterClass.Application.Builder.class);
      }

      // Construct using currencyExchangeValue.CurrencyExchangeValueOuterClass.Application.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        address_ = "";

        port_ = 0;

        currency_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Application_descriptor;
      }

      @java.lang.Override
      public currencyExchangeValue.CurrencyExchangeValueOuterClass.Application getDefaultInstanceForType() {
        return currencyExchangeValue.CurrencyExchangeValueOuterClass.Application.getDefaultInstance();
      }

      @java.lang.Override
      public currencyExchangeValue.CurrencyExchangeValueOuterClass.Application build() {
        currencyExchangeValue.CurrencyExchangeValueOuterClass.Application result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public currencyExchangeValue.CurrencyExchangeValueOuterClass.Application buildPartial() {
        currencyExchangeValue.CurrencyExchangeValueOuterClass.Application result = new currencyExchangeValue.CurrencyExchangeValueOuterClass.Application(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.address_ = address_;
        result.port_ = port_;
        if (((bitField0_ & 0x00000004) != 0)) {
          currency_ = java.util.Collections.unmodifiableList(currency_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.currency_ = currency_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof currencyExchangeValue.CurrencyExchangeValueOuterClass.Application) {
          return mergeFrom((currencyExchangeValue.CurrencyExchangeValueOuterClass.Application)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(currencyExchangeValue.CurrencyExchangeValueOuterClass.Application other) {
        if (other == currencyExchangeValue.CurrencyExchangeValueOuterClass.Application.getDefaultInstance()) return this;
        if (!other.getAddress().isEmpty()) {
          address_ = other.address_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (!other.currency_.isEmpty()) {
          if (currency_.isEmpty()) {
            currency_ = other.currency_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureCurrencyIsMutable();
            currency_.addAll(other.currency_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        currencyExchangeValue.CurrencyExchangeValueOuterClass.Application parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (currencyExchangeValue.CurrencyExchangeValueOuterClass.Application) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object address_ = "";
      /**
       * <code>string address = 1;</code>
       */
      public java.lang.String getAddress() {
        java.lang.Object ref = address_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          address_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes() {
        java.lang.Object ref = address_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          address_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder setAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        address_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder clearAddress() {
        
        address_ = getDefaultInstance().getAddress();
        onChanged();
        return this;
      }
      /**
       * <code>string address = 1;</code>
       */
      public Builder setAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        address_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>int32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>int32 port = 2;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 port = 2;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> currency_ =
        java.util.Collections.emptyList();
      private void ensureCurrencyIsMutable() {
        if (!((bitField0_ & 0x00000004) != 0)) {
          currency_ = new java.util.ArrayList<java.lang.Integer>(currency_);
          bitField0_ |= 0x00000004;
        }
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public java.util.List<currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency> getCurrencyList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency>(currency_, currency_converter_);
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public int getCurrencyCount() {
        return currency_.size();
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency getCurrency(int index) {
        return currency_converter_.convert(currency_.get(index));
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public Builder setCurrency(
          int index, currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCurrencyIsMutable();
        currency_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public Builder addCurrency(currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCurrencyIsMutable();
        currency_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public Builder addAllCurrency(
          java.lang.Iterable<? extends currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency> values) {
        ensureCurrencyIsMutable();
        for (currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency value : values) {
          currency_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public Builder clearCurrency() {
        currency_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public java.util.List<java.lang.Integer>
      getCurrencyValueList() {
        return java.util.Collections.unmodifiableList(currency_);
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public int getCurrencyValue(int index) {
        return currency_.get(index);
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public Builder setCurrencyValue(
          int index, int value) {
        ensureCurrencyIsMutable();
        currency_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public Builder addCurrencyValue(int value) {
        ensureCurrencyIsMutable();
        currency_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .currencyExchangeValue.Currency currency = 3;</code>
       */
      public Builder addAllCurrencyValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureCurrencyIsMutable();
        for (int value : values) {
          currency_.add(value);
        }
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:currencyExchangeValue.Application)
    }

    // @@protoc_insertion_point(class_scope:currencyExchangeValue.Application)
    private static final currencyExchangeValue.CurrencyExchangeValueOuterClass.Application DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new currencyExchangeValue.CurrencyExchangeValueOuterClass.Application();
    }

    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Application getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Application>
        PARSER = new com.google.protobuf.AbstractParser<Application>() {
      @java.lang.Override
      public Application parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Application(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Application> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Application> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public currencyExchangeValue.CurrencyExchangeValueOuterClass.Application getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:currencyExchangeValue.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.currencyExchangeValue.Currency currency = 1;</code>
     */
    int getCurrencyValue();
    /**
     * <code>.currencyExchangeValue.Currency currency = 1;</code>
     */
    currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency getCurrency();

    /**
     * <code>double value = 2;</code>
     */
    double getValue();
  }
  /**
   * Protobuf type {@code currencyExchangeValue.Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:currencyExchangeValue.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      currency_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              currency_ = rawValue;
              break;
            }
            case 17: {

              value_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              currencyExchangeValue.CurrencyExchangeValueOuterClass.Response.class, currencyExchangeValue.CurrencyExchangeValueOuterClass.Response.Builder.class);
    }

    public static final int CURRENCY_FIELD_NUMBER = 1;
    private int currency_;
    /**
     * <code>.currencyExchangeValue.Currency currency = 1;</code>
     */
    public int getCurrencyValue() {
      return currency_;
    }
    /**
     * <code>.currencyExchangeValue.Currency currency = 1;</code>
     */
    public currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency getCurrency() {
      @SuppressWarnings("deprecation")
      currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency result = currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency.valueOf(currency_);
      return result == null ? currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private double value_;
    /**
     * <code>double value = 2;</code>
     */
    public double getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currency_ != currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency.PLN.getNumber()) {
        output.writeEnum(1, currency_);
      }
      if (value_ != 0D) {
        output.writeDouble(2, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currency_ != currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency.PLN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, currency_);
      }
      if (value_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof currencyExchangeValue.CurrencyExchangeValueOuterClass.Response)) {
        return super.equals(obj);
      }
      currencyExchangeValue.CurrencyExchangeValueOuterClass.Response other = (currencyExchangeValue.CurrencyExchangeValueOuterClass.Response) obj;

      if (currency_ != other.currency_) return false;
      if (java.lang.Double.doubleToLongBits(getValue())
          != java.lang.Double.doubleToLongBits(
              other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENCY_FIELD_NUMBER;
      hash = (53 * hash) + currency_;
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getValue()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(currencyExchangeValue.CurrencyExchangeValueOuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code currencyExchangeValue.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:currencyExchangeValue.Response)
        currencyExchangeValue.CurrencyExchangeValueOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                currencyExchangeValue.CurrencyExchangeValueOuterClass.Response.class, currencyExchangeValue.CurrencyExchangeValueOuterClass.Response.Builder.class);
      }

      // Construct using currencyExchangeValue.CurrencyExchangeValueOuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currency_ = 0;

        value_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return currencyExchangeValue.CurrencyExchangeValueOuterClass.internal_static_currencyExchangeValue_Response_descriptor;
      }

      @java.lang.Override
      public currencyExchangeValue.CurrencyExchangeValueOuterClass.Response getDefaultInstanceForType() {
        return currencyExchangeValue.CurrencyExchangeValueOuterClass.Response.getDefaultInstance();
      }

      @java.lang.Override
      public currencyExchangeValue.CurrencyExchangeValueOuterClass.Response build() {
        currencyExchangeValue.CurrencyExchangeValueOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public currencyExchangeValue.CurrencyExchangeValueOuterClass.Response buildPartial() {
        currencyExchangeValue.CurrencyExchangeValueOuterClass.Response result = new currencyExchangeValue.CurrencyExchangeValueOuterClass.Response(this);
        result.currency_ = currency_;
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof currencyExchangeValue.CurrencyExchangeValueOuterClass.Response) {
          return mergeFrom((currencyExchangeValue.CurrencyExchangeValueOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(currencyExchangeValue.CurrencyExchangeValueOuterClass.Response other) {
        if (other == currencyExchangeValue.CurrencyExchangeValueOuterClass.Response.getDefaultInstance()) return this;
        if (other.currency_ != 0) {
          setCurrencyValue(other.getCurrencyValue());
        }
        if (other.getValue() != 0D) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        currencyExchangeValue.CurrencyExchangeValueOuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (currencyExchangeValue.CurrencyExchangeValueOuterClass.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int currency_ = 0;
      /**
       * <code>.currencyExchangeValue.Currency currency = 1;</code>
       */
      public int getCurrencyValue() {
        return currency_;
      }
      /**
       * <code>.currencyExchangeValue.Currency currency = 1;</code>
       */
      public Builder setCurrencyValue(int value) {
        currency_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.currencyExchangeValue.Currency currency = 1;</code>
       */
      public currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency getCurrency() {
        @SuppressWarnings("deprecation")
        currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency result = currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency.valueOf(currency_);
        return result == null ? currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency.UNRECOGNIZED : result;
      }
      /**
       * <code>.currencyExchangeValue.Currency currency = 1;</code>
       */
      public Builder setCurrency(currencyExchangeValue.CurrencyExchangeValueOuterClass.Currency value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        currency_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.currencyExchangeValue.Currency currency = 1;</code>
       */
      public Builder clearCurrency() {
        
        currency_ = 0;
        onChanged();
        return this;
      }

      private double value_ ;
      /**
       * <code>double value = 2;</code>
       */
      public double getValue() {
        return value_;
      }
      /**
       * <code>double value = 2;</code>
       */
      public Builder setValue(double value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double value = 2;</code>
       */
      public Builder clearValue() {
        
        value_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:currencyExchangeValue.Response)
    }

    // @@protoc_insertion_point(class_scope:currencyExchangeValue.Response)
    private static final currencyExchangeValue.CurrencyExchangeValueOuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new currencyExchangeValue.CurrencyExchangeValueOuterClass.Response();
    }

    public static currencyExchangeValue.CurrencyExchangeValueOuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public currencyExchangeValue.CurrencyExchangeValueOuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_currencyExchangeValue_Application_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_currencyExchangeValue_Application_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_currencyExchangeValue_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_currencyExchangeValue_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033CurrencyExchangeValue.proto\022\025currencyE" +
      "xchangeValue\"_\n\013Application\022\017\n\007address\030\001" +
      " \001(\t\022\014\n\004port\030\002 \001(\005\0221\n\010currency\030\003 \003(\0162\037.c" +
      "urrencyExchangeValue.Currency\"L\n\010Respons" +
      "e\0221\n\010currency\030\001 \001(\0162\037.currencyExchangeVa" +
      "lue.Currency\022\r\n\005value\030\002 \001(\001*%\n\010Currency\022" +
      "\007\n\003PLN\020\000\022\007\n\003USD\020\001\022\007\n\003EUR\020\0022l\n\025CurrencyEx" +
      "changeValue\022S\n\010Register\022\".currencyExchan" +
      "geValue.Application\032\037.currencyExchangeVa" +
      "lue.Response\"\0000\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_currencyExchangeValue_Application_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_currencyExchangeValue_Application_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_currencyExchangeValue_Application_descriptor,
        new java.lang.String[] { "Address", "Port", "Currency", });
    internal_static_currencyExchangeValue_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_currencyExchangeValue_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_currencyExchangeValue_Response_descriptor,
        new java.lang.String[] { "Currency", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
