# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CurrencyExchangeValue.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CurrencyExchangeValue.proto',
  package='currencyExchangeValue',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1b\x43urrencyExchangeValue.proto\x12\x15\x63urrencyExchangeValue\"_\n\x0b\x41pplication\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x31\n\x08\x63urrency\x18\x03 \x03(\x0e\x32\x1f.currencyExchangeValue.Currency\"L\n\x08Response\x12\x31\n\x08\x63urrency\x18\x01 \x01(\x0e\x32\x1f.currencyExchangeValue.Currency\x12\r\n\x05value\x18\x02 \x01(\x01*%\n\x08\x43urrency\x12\x07\n\x03PLN\x10\x00\x12\x07\n\x03USD\x10\x01\x12\x07\n\x03\x45UR\x10\x02\x32l\n\x15\x43urrencyExchangeValue\x12S\n\x08Register\x12\".currencyExchangeValue.Application\x1a\x1f.currencyExchangeValue.Response\"\x00\x30\x01\x62\x06proto3')
)

_CURRENCY = _descriptor.EnumDescriptor(
  name='Currency',
  full_name='currencyExchangeValue.Currency',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EUR', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=229,
  serialized_end=266,
)
_sym_db.RegisterEnumDescriptor(_CURRENCY)

Currency = enum_type_wrapper.EnumTypeWrapper(_CURRENCY)
PLN = 0
USD = 1
EUR = 2



_APPLICATION = _descriptor.Descriptor(
  name='Application',
  full_name='currencyExchangeValue.Application',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='currencyExchangeValue.Application.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='currencyExchangeValue.Application.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currency', full_name='currencyExchangeValue.Application.currency', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=149,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='currencyExchangeValue.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='currencyExchangeValue.Response.currency', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='currencyExchangeValue.Response.value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=227,
)

_APPLICATION.fields_by_name['currency'].enum_type = _CURRENCY
_RESPONSE.fields_by_name['currency'].enum_type = _CURRENCY
DESCRIPTOR.message_types_by_name['Application'] = _APPLICATION
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['Currency'] = _CURRENCY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Application = _reflection.GeneratedProtocolMessageType('Application', (_message.Message,), dict(
  DESCRIPTOR = _APPLICATION,
  __module__ = 'CurrencyExchangeValue_pb2'
  # @@protoc_insertion_point(class_scope:currencyExchangeValue.Application)
  ))
_sym_db.RegisterMessage(Application)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'CurrencyExchangeValue_pb2'
  # @@protoc_insertion_point(class_scope:currencyExchangeValue.Response)
  ))
_sym_db.RegisterMessage(Response)



_CURRENCYEXCHANGEVALUE = _descriptor.ServiceDescriptor(
  name='CurrencyExchangeValue',
  full_name='currencyExchangeValue.CurrencyExchangeValue',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=268,
  serialized_end=376,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='currencyExchangeValue.CurrencyExchangeValue.Register',
    index=0,
    containing_service=None,
    input_type=_APPLICATION,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CURRENCYEXCHANGEVALUE)

DESCRIPTOR.services_by_name['CurrencyExchangeValue'] = _CURRENCYEXCHANGEVALUE

# @@protoc_insertion_point(module_scope)
