# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import CurrencyExchangeValue_pb2 as CurrencyExchangeValue__pb2


class CurrencyExchangeValueStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Register = channel.unary_stream(
        '/currencyExchangeValue.CurrencyExchangeValue/Register',
        request_serializer=CurrencyExchangeValue__pb2.Application.SerializeToString,
        response_deserializer=CurrencyExchangeValue__pb2.Response.FromString,
        )


class CurrencyExchangeValueServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyExchangeValueServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Register': grpc.unary_stream_rpc_method_handler(
          servicer.Register,
          request_deserializer=CurrencyExchangeValue__pb2.Application.FromString,
          response_serializer=CurrencyExchangeValue__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'currencyExchangeValue.CurrencyExchangeValue', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
